@{
    Severity=@('Error','Warning')
    ExcludeRules=@('PSUseApprovedVerbs',
        'PSUseSingularNouns',
        'PSAvoidUsingInvokeExpression',
        'PSAvoidUsingPositionalParameters',
        'PSAvoidUsingWMICmdlet',
        'PSAvoidUsingWriteHost',
        'PSReviewUnusedParameter')
}